import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Header } from "@/components/client-components/Header";
import { shadesOfPurple } from "@clerk/themes";
import { Footer } from "@/components/server-components/Footer";
import { SavedJobProvider } from "@/context/SavedJobContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Jobingo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
      }}
    >
      <html lang="en">
        <SavedJobProvider>
          <body
            className={`${inter.className} container px-4 md:mx-8 dark text-white`}
          >
            <Header />
            {children}
            <Footer />
          </body>
        </SavedJobProvider>
      </html>
    </ClerkProvider>
  );
}
